name: Build and deploy
# on: [workflow_dispatch]
on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: szaki/devops_25o:latest

  deploy:
    needs: build-and-publish
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Check rsync
        run: rsync --version

      - name: Sync project to server
        run: |
          rsync -avz \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "ssh_key" \
            -e "ssh -i ./ssh_key -o StrictHostKeyChecking=no" \
            ./ $SERVER_USER@$SERVER_HOST:~/devops_25o
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}

      - name: SSH and deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops_25o
            docker compose pull
            docker compose up -d --remove-orphans --pull always --force-recreate
            docker image prune -f
