name: Tests
on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  unit:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Enable Yarn
        run: corepack enable yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:unit

  e2e:
    needs: unit
    name: End-to-End Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Enable Yarn
        run: corepack enable yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn test:e2e
